config: !!python/object/new:easydict.EasyDict
  dictitems:
    DATA: &id008 !!python/object/new:easydict.EasyDict
      dictitems:
        dataset: tankstemples
        evaluation_resolution: 64
        feature_grid_resolution: 64
        grid_resolution: 64
        grid_resolution_load: 64
        key: outlier_depth
        load_smooth: true
        noise: 0.001
        noise_scale: 0.01
        outlier_fraction: 0.99
        outlier_scale: 5
        resx: 320
        resy: 240
        samples: 500
        scene: ignatius
        sparsity: 0.01
        stereo_method: geometric
        test_list: family
        train_list: ignatius
        val_key: depth
        val_list: ignatius
      state:
        dataset: tankstemples
        evaluation_resolution: 64
        feature_grid_resolution: 64
        grid_resolution: 64
        grid_resolution_load: 64
        key: outlier_depth
        load_smooth: true
        noise: 0.001
        noise_scale: 0.01
        outlier_fraction: 0.99
        outlier_scale: 5
        resx: 320
        resy: 240
        samples: 500
        scene: ignatius
        sparsity: 0.01
        stereo_method: geometric
        test_list: family
        train_list: ignatius
        val_key: depth
        val_list: ignatius
    DATABASE: &id009 !!python/object/new:easydict.EasyDict
      dictitems:
        evaluation_resolution: 64
        feature_grid_resolution: 64
        grid_resolution: 64
        grid_resolution_load: 64
        n_features: 9
        repeat: 10
      state:
        evaluation_resolution: 64
        feature_grid_resolution: 64
        grid_resolution: 64
        grid_resolution_load: 64
        n_features: 9
        repeat: 10
    LOSS: &id010 !!python/object/new:easydict.EasyDict
      dictitems:
        clamp: true
        clamp_est: false
        cls: true
        lambda_conf: 0.0005
        latent_grad: false
        latent_reg: true
        mask: all
        mask_dilation_iterations: 0
        max_clamp: 0.06
        min_clamp: -0.06
        pipeline: null
        ratio: 0.03
        reinitialize: true
        renderer: &id001 !!python/object/new:easydict.EasyDict
          dictitems:
            band_weight: 5.0
            occ_weight: 30.0
            weight_thr: 0.1
          state:
            band_weight: 5.0
            occ_weight: 30.0
            weight_thr: 0.1
        scale: 1000.0
        sdf: false
        weighting: false
        wl1: 1.0
        wl2: 10.0
        wlgrad: 1.0e-06
        wln: 0.01
        wlocc: 0.01
        wlreg: 0.05
      state:
        clamp: true
        clamp_est: false
        cls: true
        lambda_conf: 0.0005
        latent_grad: false
        latent_reg: true
        mask: all
        mask_dilation_iterations: 0
        max_clamp: 0.06
        min_clamp: -0.06
        pipeline: null
        ratio: 0.03
        reinitialize: true
        renderer: *id001
        scale: 1000.0
        sdf: false
        weighting: false
        wl1: 1.0
        wl2: 10.0
        wlgrad: 1.0e-06
        wln: 0.01
        wlocc: 0.01
        wlreg: 0.05
    OPTIMIZATION: &id011 !!python/object/new:easydict.EasyDict
      dictitems:
        alternate: false
        burn_in: 10
        clip: true
        curriculum: false
        frequency: 5
        joint: false
        mask_switch: 0
        pipeline: &id002 !!python/object/new:easydict.EasyDict
          dictitems:
            alpha: 0.99
            eps: 1.0e-10
            lr: 0.01
            momentum: 0.9
            start: 0
            step_size: 2000
            weight_decay: 0.0
          state:
            alpha: 0.99
            eps: 1.0e-10
            lr: 0.01
            momentum: 0.9
            start: 0
            step_size: 2000
            weight_decay: 0.0
        renderer: &id003 !!python/object/new:easydict.EasyDict
          dictitems:
            alpha: 0.99
            eps: 1.0e-10
            lr: 0.01
            momentum: 0.9
            start: 10
            step_size: 2000
            weight_decay: 0.0
          state:
            alpha: 0.99
            eps: 1.0e-10
            lr: 0.01
            momentum: 0.9
            start: 10
            step_size: 2000
            weight_decay: 0.0
        scheduler: &id004 !!python/object/new:easydict.EasyDict
          dictitems:
            cooldown: 5
            gamma: 0.999
            mode: max
            patience: 20
            schedule: true
            threshold: 0.01
            threshold_mode: rel
          state:
            cooldown: 5
            gamma: 0.999
            mode: max
            patience: 20
            schedule: true
            threshold: 0.01
            threshold_mode: rel
      state:
        alternate: false
        burn_in: 10
        clip: true
        curriculum: false
        frequency: 5
        joint: false
        mask_switch: 0
        pipeline: *id002
        renderer: *id003
        scheduler: *id004
    PIPELINE: &id012 !!python/object/new:easydict.EasyDict
      dictitems:
        FUSION: &id005 !!python/object/new:easydict.EasyDict
          dictitems:
            activation: torch.nn.Tanh()
            depth: true
            direction: true
            encoder_filter_size: 3
            extraction: nearest
            integration: nearest
            n_layers: 1
            n_samples: 6
            net: FusionNet
            normalization: layer
            position: false
            resx: 320
            resy: 240
            uncertainty: false
          state:
            activation: torch.nn.Tanh()
            depth: true
            direction: true
            encoder_filter_size: 3
            extraction: nearest
            integration: nearest
            n_layers: 1
            n_samples: 6
            net: FusionNet
            normalization: layer
            position: false
            resx: 320
            resy: 240
            uncertainty: false
        RENDERER: &id006 !!python/object/new:easydict.EasyDict
          dictitems:
            activation: torch.nn.Tanh()
            conf_head: false
            kernel: 5
            mode: float
            normal_head: false
            occ_head: true
            output_scale: 0.06
            sdf_head: true
            superresolve: false
          state:
            activation: torch.nn.Tanh()
            conf_head: false
            kernel: 5
            mode: float
            normal_head: false
            occ_head: true
            output_scale: 0.06
            sdf_head: true
            superresolve: false
        minimal_gpu: false
        n_features: 9
        renderer: standard
        routing: false
        routing_threshold: 0.8
        superresolution: false
        update: true
        use_count: false
        use_count_renderer: false
      state:
        FUSION: *id005
        RENDERER: *id006
        minimal_gpu: false
        n_features: 9
        renderer: standard
        routing: false
        routing_threshold: 0.8
        superresolution: false
        update: true
        use_count: false
        use_count_renderer: false
    SETTINGS: &id013 !!python/object/new:easydict.EasyDict
      dictitems:
        data_path: /cluster/project/infk/cvg/weders/data/tankstemples/training
        experiment_path: /cluster/project/infk/cvg/weders/projects/002/experiments_clean
        name: tanks_and_temples_nocount
      state:
        data_path: /cluster/project/infk/cvg/weders/data/tankstemples/training
        experiment_path: /cluster/project/infk/cvg/weders/projects/002/experiments_clean
        name: tanks_and_temples_nocount
    TESTING: &id014 !!python/object/new:easydict.EasyDict
      dictitems:
        batch_size: 1
        prefix: configs/tests
        shuffle: false
        tests: &id007
        - shapenet.plane.noise.00.yaml
        - shapenet.plane.noise.005.yaml
      state:
        batch_size: 1
        prefix: configs/tests
        shuffle: false
        tests: *id007
    TRAINING: &id015 !!python/object/new:easydict.EasyDict
      dictitems:
        accumulate_steps: 8
        batch_size: 1
        interpolation: true
        latent_noise: false
        n_epochs: 200
        n_points: 4
        oversampling: false
        shuffle: true
        stop_batch: -1
      state:
        accumulate_steps: 8
        batch_size: 1
        interpolation: true
        latent_noise: false
        n_epochs: 200
        n_points: 4
        oversampling: false
        shuffle: true
        stop_batch: -1
    VALIDATION: &id016 !!python/object/new:easydict.EasyDict
      dictitems:
        batch_size: 1
        shuffle: true
      state:
        batch_size: 1
        shuffle: true
  state:
    DATA: *id008
    DATABASE: *id009
    LOSS: *id010
    OPTIMIZATION: *id011
    PIPELINE: *id012
    SETTINGS: *id013
    TESTING: *id014
    TRAINING: *id015
    VALIDATION: *id016
